// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2BX9hFdXzHpWeGSGosFsvg_G69a31v2o',
    appId: '1:578848477881:web:2841387a25a180c7264168',
    messagingSenderId: '578848477881',
    projectId: 'smokstop-a6464',
    authDomain: 'smokstop-a6464.firebaseapp.com',
    storageBucket: 'smokstop-a6464.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXZDEhu7HQqLn2hmqp3y7U-o0c1RhiB0',
    appId: '1:578848477881:android:b9b9f2d515ba67ed264168',
    messagingSenderId: '578848477881',
    projectId: 'smokstop-a6464',
    storageBucket: 'smokstop-a6464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWCfKORSqlE55E1MP_QaFN1mAgzqumS4',
    appId: '1:578848477881:ios:cf14d76272e75909264168',
    messagingSenderId: '578848477881',
    projectId: 'smokstop-a6464',
    storageBucket: 'smokstop-a6464.appspot.com',
    iosClientId: '578848477881-c1195oh1otbaoe5dtoh4s856btustoh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.stopsmok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpWCfKORSqlE55E1MP_QaFN1mAgzqumS4',
    appId: '1:578848477881:ios:cf14d76272e75909264168',
    messagingSenderId: '578848477881',
    projectId: 'smokstop-a6464',
    storageBucket: 'smokstop-a6464.appspot.com',
    iosClientId: '578848477881-c1195oh1otbaoe5dtoh4s856btustoh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.stopsmok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2BX9hFdXzHpWeGSGosFsvg_G69a31v2o',
    appId: '1:578848477881:web:e387824a50ad9c36264168',
    messagingSenderId: '578848477881',
    projectId: 'smokstop-a6464',
    authDomain: 'smokstop-a6464.firebaseapp.com',
    storageBucket: 'smokstop-a6464.appspot.com',
  );

}